# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'
max_jobs: 1
image: WMF 5
# History plugin requires complete log
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version: master
  au_push: true
  # Force test: use 1 to test all, or N to split testing into N groups
  au_test_groups: 1

  # Github token to commit pushed packages to repository
  github_user_repo: JourneyOver/chocolatey-packages
  github_api_key:
    secure: pjjxVtx3PPBrCQGTPgRgG6AZS55C0yq5tfRmUgUU+7yOixqxSvPZRgVYG0zt7nzx #https://ci.appveyor.com/tools/encrypt

  github_username: JourneyOver
  github_password:
    secure: NTaQtg1cKJNu44zgrQ4loQ==

  # Mail credentials - for error notifications
  mail_user: timtag1190@gmail.com
  mail_pass:
    secure: RJY8Wmf67GuBcVHhZviMdg== #https://ci.appveyor.com/tools/encrypt
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id: 508bb89c4cc35b67842940c60310532b

  # Force test: gist id for test results
  gist_id_test: 13f08beca5db513521762b5c4ce53d58

  # Chocolatey API key - to push updated packages
  api_key:
    secure: 2NnnfrwVZD5wmP4ZEW3sAV6QLMv3gsRrRWWnQ2++lXudfmGhi9M1yjjD2DnDOaXr # https://ci.appveyor.com/tools/encrypt

init:
- git config --global user.email "timtag1190@gmail.com"
- git config --global user.name "JourneyOver"
- git config --global core.safecrlf false

install:
- ps: |
    #Chocolatey version check and update if there is one.
      $chocov = choco --version
      $versions = Invoke-Webrequest -UseBasicParsing `
          "https://chocolatey.org/api/v2/package-versions/chocolatey" |
        Select-Object -Expand Content  | ConvertFrom-Json
      $newestVersion = $versions[-1]

      If ($chocov -eq "$newestVersion") {
        write-host Chocolatey is up to date
      } Else {
        choco upgrade chocolatey > $null
      }
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- cinst autohotkey.portable chocolatey-core.extension > $null
- choco --version
- ps: |
    git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
    . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

build_script:
- ps: |
    $ErrorActionPreference = 'Continue'

    if ($Env:APPVEYOR_PROJECT_NAME  -like '*test*') { ./test_all.ps1 "random $Env:au_test_groups"; return }

    if ( ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') -and ($Env:APPVEYOR_FORCED_BUILD -ne 'true') ) {
        switch -regex ($Env:APPVEYOR_REPO_COMMIT_MESSAGE)
        {
            '\[AU (.+?)\]'   { $forced = $Matches[1] }

            '\[PUSH (.+?)\]' {
                $packages = $Matches[1] -split ' '
                Write-Host "PUSHING PACKAGES: $packages"
                foreach ($package in $packages) {
                    Write-Host ("{0}`n{1}`n" -f ('-'*60), "PACKAGE: $package")
                    $package_dir = ls -recurse | ? { $_.Name -eq "$package.nuspec"} | select -First 1 | % Directory
                    if (!$package_dir) { Write-Warning "Can't find package '$package'"; continue }
                    pushd $package_dir
                      if (Test-Path update.ps1 -ea 0) { ./update.ps1 }
                      choco pack; Push-Package;
                    popd
                }
                return
            }
        }
    }

    ./update_all.ps1 -ForcedPackages $forced
    7z a au_temp.zip $Env:TEMP\chocolatey\au\*

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md
- path: Update-History.md
- path: au_temp.zip

notifications:
- provider: Email
  to:
  - $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
