version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - master
skip_tags: true
skip_branch_with_pr: true
image:
- Visual Studio 2017
- Visual Studio 2015

init:
- cmd: |
    git config --global user.email "timtag1190@gmail.com"
    git config --global user.name "JourneyOver"
    git config --global core.safecrlf false

- ps: Set-Service wuauserv -StartupType Manual

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version: master
  au_push: false

  # Github token to commit pushed packages to repository
  github_user_repo: JourneyOver/chocolatey-packages
  github_api_key:
    secure: pjjxVtx3PPBrCQGTPgRgG6AZS55C0yq5tfRmUgUU+7yOixqxSvPZRgVYG0zt7nzx

  #ID of the gist used to save test run results
  gist_id: c14815ee16a432c8215f3f63fb8b7133

  #Chocolatey version we want to use when checking for updates.
  choco_version: '0.10.8'
  nupkg_cache_path: C:\nupkg_cache

install:
- ps: |
    if (!(Test-Path "$env:nupkg_cache_path")) { mkdir -Force "$env:nupkg_cache_path" }
    @{
      'chocolatey' = $Env:choco_version
      'wormies-au-helpers' = '0.3.2'
    }.GetEnumerator() | % {
      if (!(Test-Path "${env:nupkg_cache_path}\$($_.Key).$($_.Value).nupkg")) { rm "${env:nupkg_cache_path}\$($_.Key).*.nupkg" ; iwr "https://chocolatey.org/api/v2/package/$($_.Key)/$($_.Value)" -OutFile "${env:nupkg_cache_path}\$($_.Key).$($_.Value).nupkg" }
      if ($_.Key -eq 'chocolatey') { cup $_.Key --version $_.Value --source ${env:nupkg_cache_path} --allow-downgrade }
      else { cinst $_.Key --version $_.Value --source ${env:nupkg_cache_path} --ignore-dependencies }
    }
    Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- cmd: git --version
- cmd: choco --version
- ps: |
    git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
    . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

cache: C:\nupkg_cache
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build: off

test_script:
- ps: |
    if ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') {
      .\scripts\Invoke-PesterTests.ps1
    }
    else {
      .\scripts\Invoke-PesterTests.ps1 -runAllTests
    }
deploy: off
#on_failure:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
- ps: gci -Recurse "*.nupkg" | % { Push-AppveyorArtifact $_ }
